### ISSUE TITLE
Syntax error on file mdmsoft/yii2-admin/components/AccessControl.php

### ISSUE THREAD

**Issue by bot209** [mdmsoft/yii2-admin#473] opened 2022-10-06 13:37 UTC
![image](https://user-images.githubusercontent.com/92056568/194327459-3ab8349c-bfa6-4e53-9e47-214ae60ce946.png)

Need to add an opening bracket before the string. Package version 2.12.

**Comment by mtangoo** [comment] 2022-10-22 21:05
This error is not fixed yet!
I wonder why, being such a simple thing to do.

**Comment by mtangoo** [comment] 2022-10-22 21:06
duplicate of #471

**Comment by sihar** [comment] 2022-10-27 03:37
thanks for the report. Issue solved using [this PR](https://github.com/mdmsoft/yii2-admin/pull/472)

**Closed by sihar** 2022-10-27 03:37 UTC
